// AUTO-GENERATED by scripts/build-content.ts. Do not edit.
import type { ParsedComponent } from '@/lib/types'
import components from './components.generated.json'
import opTemplates from './optemplates.generated.json'
import skeletons from './skeletons.generated.json'
import pullSheets from './pullsheets.generated.json'
import atoms from './atoms.generated.json'

export const COMPONENTS = components as ParsedComponent[]
export const OP_TEMPLATES = opTemplates as ParsedComponent[]
export const SKELETONS = skeletons as ParsedComponent[]
export const PULL_SHEETS = pullSheets as ParsedComponent[]
export const ATOMS = atoms as ParsedComponent[]
export const ALL_CONTENT = [...COMPONENTS, ...OP_TEMPLATES, ...SKELETONS, ...PULL_SHEETS, ...ATOMS]
